# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dixy - דיקסי
title: Dixy
# email: xcode2vlad@gmail.com
# website: github.com/vrahmanov

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: NONE
# github_username:  vrahmanov
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: NONE
# linkedin_username: vladi-rahmanov
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: NONE
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://github.com/vrahmanov

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/test.png
about_content: | # this will include new lines to allow paragraphs
  Name: dixy 
  Y-born: 2022
  Owner : Romy
  Geographic Area: Raanana

content:
  - title: About me - קצת עליי # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Raanana - רעננה
        # link: https://github.com/vrahmanov?tab=repositories
        # link_text: Project Website
        # additional_links:
        #   - title:  gist
        #     icon: fab fa-github
        #     url: https://github.com/vrahmanov?tab=repositories
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   Over the past century , i have been forking and supporting multiple projects , privately and publicly , im proud of each one of them. 
        # description: | # this will include new lines to allow paragraphs
        #   I like to make automation go above and beyond the basic needs , from local to remote , from onprem to multicloud - you name it, i probably met it.

  - title: Languages # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Hebrew

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
